;Generated by the original T compiler

jmp .main


.hold ;()

        .hold_loop
        jmp .hold_loop
    pop pc

.print ;(x:array[u8?70])
ubl ay 0x0F0000
mov ay ax ;ax = x[0]
pop pc

.main ;()
ldi ay 3
ubs ay 0x0F0046 ;chars[0] = 3
ldi ay 20
ubs ay 0x0F0047 ;chars[1] = 20
ldi ay 100
ubs ay 0x0F0048 ;chars[2] = 100
ldi ay 69420
sto ay 0x0F008C ;nums[0] = 69420
ldi ay 0x00FFFF
sto ay 0x0F0090 ;nums[1] = 0xFFFF
ldi ay 13
sto ay 0x0F0094 ;nums[2] = 13
ldi ay 16
sto ay 0x0F0098 ;nums[3] = 16
ldi ay 69
sto ay 0x0F009C ;nums[4] = 69
ldi ay 4
mov ay cx
sto cx 0x0F01A4 ;x = 4
lod cx 0x0F01A4
mov cx ay
ldi ax 4
mul ar
mov ar ax
ldi ar 0x0F008C
add ax
lor ay 0 ar
sto ay 0x0F01A6 ;w = nums[x]
lod ay 0x0F01A6
mov ay bx ;bx = w
mov pc ar
ldi ax 16
add ax
psh ar
jmp .hold ;hold();
pop pc

