;Generated by the original T compiler

jmp .main


.hold ;()

        jmp .hold
    pop pc

.print ;(x:array[u8?70])
ubl ay 0x0F0000
mov ay ax ;ax = x[0]
pop pc

.main ;()
ldi ay 3
ubs ay 0x0F0046 ;chars[0] = 3
ldi ay 20
ubs ay 0x0F0047 ;chars[1] = 20
ldi ay 100
ubs ay 0x0F0048 ;chars[2] = 100
ldi cr 0
ldi by 0x000046
ldi ar 0x0F0046
.loading_loop_id:_0xFE8ECA2320ADBFDB
cmp .exit_loop_id:_0xFE8ECA2320ADBFDB
lbr ax 0 ar
psh ax
inc cr
inc ar
jmp .loading_loop_id:_0xFE8ECA2320ADBFDB
.exit_loop_id:_0xFE8ECA2320ADBFDB
ldi cr 0
ldi by 0x000046
ldi ar 0x0F0000
.loading_loop_id:_0xC6E7B553F787CC02
cmp .exit_loop_id:_0xC6E7B553F787CC02
pop ax
sbr ax 0 ar
inc cr
inc ar
jmp .loading_loop_id:_0xC6E7B553F787CC02
.exit_loop_id:_0xC6E7B553F787CC02
mov pc ar
ldi ax 16
add ax
psh ar
jmp .print ;print(x:chars);
mov pc ar
ldi ax 16
add ax
psh ar
jmp .hold ;hold();
pop pc

